### 1교시 - 이론

### 2교시

In [1]:
import numpy as np

In [2]:
a = np.ndarray((2, 3))
a

array([[ 4.63939877e-308, -5.64938534e+036, -1.78409531e+046],
       [-4.32950182e-035, -8.72433218e-026, -1.57234264e-063]])

In [3]:
a = np.ndarray((2, 3), dtype=int)
a

array([[   9198723453795908, 5156903189229060492, 5298766577360225733],
       [4092864156735161052, 4231976415668524376, 3667252571916326280]])

In [4]:
a = np.ndarray((3, 2), dtype=int)
a

array([[    9198723453795908, -4066468847625715316],
       [-3924605459494550075, -5130507880119614756],
       [-4991395621186251432, -5556119464938449528]])

In [5]:
# help(np.ndarray)
np.ndarray?

Init signature: np.ndarray(self, /, *args, **kwargs)
Docstring:     
ndarray(shape, dtype=float, buffer=None, offset=0,
        strides=None, order=None)

An array object represents a multidimensional, homogeneous array
of fixed-size items.  An associated data-type object describes the
format of each element in the array (its byte-order, how many bytes it
occupies in memory, whether it is an integer, a floating point number,
or something else, etc.)

Arrays should be constructed using `array`, `zeros` or `empty` (refer
to the See Also section below).  The parameters given here refer to
a low-level method (`ndarray(...)`) for instantiating an array.

For more information, refer to the `numpy` module and examine the
methods and attributes of an array.

Parameters
----------
(for the __new__ method; see Notes below)

shape : tuple of ints
    Shape of created array.
dtype : data-type, optional
    Any object that can be interpreted as a numpy data type.
buffer : object exposing buffer int

In [8]:
a = np.ndarray(shape=(3, 2), dtype=int)
a

array([[25895968444448860, 30962749956620365],
       [29555349301231732, 27303403461017710],
       [28429415035764846, 14355657603940466]])

In [11]:
print(a.shape)
print(a.ndim)
print(a.size)
print(a.itemsize)
print(a.dtype)
print(a.nbytes)

(3, 2)
2
6
8
int64
48


In [12]:
a.data

In [14]:
a = np.array([1, 2, 3], dtype=int)
a

array([1, 2, 3])

In [15]:
type(a)

numpy.ndarray

In [17]:
print(a.shape)
print(a.ndim)
print(a.dtype)
print(a.size)
# byte size
print(a.itemsize)
print(a.nbytes)

(3,)
1
int64
3
8
24


In [22]:
# list 형태 []로 입력해야함
# np.array([1, 2, 3])
np.array(1, 2, 3)

TypeError: array() takes from 1 to 2 positional arguments but 3 were given

In [19]:
np.array([1, 'py', 3.14])

array(['1', 'py', '3.14'], dtype='<U32')

In [24]:
unicode_array = np.array(['가', '나', '다'], dtype='<U32')
unicode_array

array(['가', '나', '다'], dtype='<U32')

In [27]:
unicode_array = np.array(['가나다라마바'*8, '나', '다'], dtype='<U32')
unicode_array

array(['가나다라마바가나다라마바가나다라마바가나다라마바가나다라마바가나', '나', '다'], dtype='<U32')

In [28]:
lang = np.array(['python', 'java', 'c'])
lang

array(['python', 'java', 'c'], dtype='<U6')

In [30]:
a = np.array((1, 2, 3), dtype=float)
a

array([1., 2., 3.])

In [31]:
# float 통일
b = np.array((1, 2.2, 3))
b

array([1. , 2.2, 3. ])

In [33]:
print(np.arange(3))
print(np.arange(3, 7))
print(np.arange(3, 7, 2))

[0 1 2]
[3 4 5 6]
[3 5]


In [34]:
print(np.arange(2.0))
print(np.arange(2.0, 5.6))
print(np.arange(2.0, 5.6, 0.8))

[0. 1.]
[2. 3. 4. 5.]
[2.  2.8 3.6 4.4 5.2]


In [37]:
np.arange(0, 2, 0.5, dtype=int)

array([0, 0, 0, 0])

In [38]:
np.arange(0, 2, 0.5)

array([0. , 0.5, 1. , 1.5])

In [41]:
np.arange(-2, 2, 0.5, dtype=int)

array([-2, -1,  0,  1,  2,  3,  4,  5])

In [42]:
np.arange(-2, 2, 0.5)

array([-2. , -1.5, -1. , -0.5,  0. ,  0.5,  1. ,  1.5])

In [45]:
np.arange(12).reshape(3, 5)

ValueError: cannot reshape array of size 12 into shape (3,5)

In [48]:
a = np.arange(12).reshape(3, 4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [50]:
np.reshape(a, (2, 6))

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11]])

In [51]:
b = np.array([1, 2, 3, 4, 5, 6]).reshape(3, 2)
b

array([[1, 2],
       [3, 4],
       [5, 6]])

In [57]:
print(b.shape)
np.reshape(b, (2, -1))

(3, 2)


array([[1, 2, 3],
       [4, 5, 6]])

In [58]:
np.linspace(2.0, 3.0)

array([2.        , 2.02040816, 2.04081633, 2.06122449, 2.08163265,
       2.10204082, 2.12244898, 2.14285714, 2.16326531, 2.18367347,
       2.20408163, 2.2244898 , 2.24489796, 2.26530612, 2.28571429,
       2.30612245, 2.32653061, 2.34693878, 2.36734694, 2.3877551 ,
       2.40816327, 2.42857143, 2.44897959, 2.46938776, 2.48979592,
       2.51020408, 2.53061224, 2.55102041, 2.57142857, 2.59183673,
       2.6122449 , 2.63265306, 2.65306122, 2.67346939, 2.69387755,
       2.71428571, 2.73469388, 2.75510204, 2.7755102 , 2.79591837,
       2.81632653, 2.83673469, 2.85714286, 2.87755102, 2.89795918,
       2.91836735, 2.93877551, 2.95918367, 2.97959184, 3.        ])

In [59]:
np.linspace(2.0, 3.0, retstep=True)

(array([2.        , 2.02040816, 2.04081633, 2.06122449, 2.08163265,
        2.10204082, 2.12244898, 2.14285714, 2.16326531, 2.18367347,
        2.20408163, 2.2244898 , 2.24489796, 2.26530612, 2.28571429,
        2.30612245, 2.32653061, 2.34693878, 2.36734694, 2.3877551 ,
        2.40816327, 2.42857143, 2.44897959, 2.46938776, 2.48979592,
        2.51020408, 2.53061224, 2.55102041, 2.57142857, 2.59183673,
        2.6122449 , 2.63265306, 2.65306122, 2.67346939, 2.69387755,
        2.71428571, 2.73469388, 2.75510204, 2.7755102 , 2.79591837,
        2.81632653, 2.83673469, 2.85714286, 2.87755102, 2.89795918,
        2.91836735, 2.93877551, 2.95918367, 2.97959184, 3.        ]),
 np.float64(0.02040816326530612))

In [60]:
np.linspace(2.0, 3.0, endpoint=False, retstep=True)

(array([2.  , 2.02, 2.04, 2.06, 2.08, 2.1 , 2.12, 2.14, 2.16, 2.18, 2.2 ,
        2.22, 2.24, 2.26, 2.28, 2.3 , 2.32, 2.34, 2.36, 2.38, 2.4 , 2.42,
        2.44, 2.46, 2.48, 2.5 , 2.52, 2.54, 2.56, 2.58, 2.6 , 2.62, 2.64,
        2.66, 2.68, 2.7 , 2.72, 2.74, 2.76, 2.78, 2.8 , 2.82, 2.84, 2.86,
        2.88, 2.9 , 2.92, 2.94, 2.96, 2.98]),
 np.float64(0.02))

In [61]:
print((3 - 2) / 50)

0.02


In [62]:
np.linspace(2.0, 3.0, num=5, retstep=True)

(array([2.  , 2.25, 2.5 , 2.75, 3.  ]), np.float64(0.25))

In [63]:
np.linspace(2.0, 3.0, num=5, retstep=True, endpoint=False)

(array([2. , 2.2, 2.4, 2.6, 2.8]), np.float64(0.2))

In [66]:
# array는 -1값까지 출력이지만 부동소수점 문제로 인해 0.4도 출력됨
np.arange(0.1, 0.4, 0.1)

array([0.1, 0.2, 0.3, 0.4])

In [67]:
np.arange(1, 4, 1) / 10.0

array([0.1, 0.2, 0.3])

In [68]:
np.linspace(0.1, 0.4, 3, endpoint=False)

array([0.1, 0.2, 0.3])

In [69]:
np.linspace(0.1, 0.4, 4)

array([0.1, 0.2, 0.3, 0.4])

In [71]:
a = np.zeros(5)
a

array([0., 0., 0., 0., 0.])

In [73]:
a.dtype

dtype('float64')

In [74]:
a = np.zeros(5, dtype=int)
a

array([0, 0, 0, 0, 0])

In [76]:
a.dtype

dtype('int64')

In [77]:
b = np.zeros((2, 1))
b

array([[0.],
       [0.]])

In [78]:
b.shape

(2, 1)

In [80]:
np.ones((2, 4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [81]:
np.ones((2, 4), dtype=int)

array([[1, 1, 1, 1],
       [1, 1, 1, 1]])

In [82]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [83]:
np.eye(3, dtype=int)

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [85]:
np.eye(3, 5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.]])

In [86]:
np.eye(3, 5, 1)

array([[0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.]])

In [87]:
np.eye(3, 5, -1)

array([[0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.]])

In [88]:
np.eye(3, 5, -2)

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0.]])

In [90]:
np.full([2, 3], 9)

array([[9, 9, 9],
       [9, 9, 9]])

In [91]:
np.full([2, 3], (1, 2, 3))

array([[1, 2, 3],
       [1, 2, 3]])

In [92]:
# 2x4 행렬이지만 원소의 개수가 3개
np.full([2, 4], (1, 2, 3))

ValueError: could not broadcast input array from shape (3,) into shape (2,4)

In [95]:
np.full([3, 4], range(4))

array([[0, 1, 2, 3],
       [0, 1, 2, 3],
       [0, 1, 2, 3]])

In [100]:
np.full([4, 3], fill_value=np.arange(3))

array([[0, 1, 2],
       [0, 1, 2],
       [0, 1, 2],
       [0, 1, 2]])

In [96]:
# reshape가 없으면 원소 개수가 달라서 오류발생
np.full([4, 3], fill_value=np.arange(4).reshape(4, 1))

array([[0, 0, 0],
       [1, 1, 1],
       [2, 2, 2],
       [3, 3, 3]])

In [103]:
np.empty(3)

array([0.e+000, 5.e-324, 1.e-323])

In [104]:
np.empty([2, 3])

array([[3.92689863e-061, 1.05033086e-046, 2.44598998e-056],
       [1.06187958e-046, 3.69285499e-057, 1.78005909e-306]])

In [124]:
np.empty([2, 3], dtype=int)

array([[3703139091528169316, 3919029089387753570, 3774915000870986081],
       [3919088475193161015, 3762526799220275200,   32651097298501632]])

In [129]:
np.empty([3, 2], dtype=int)

array([[[            0, 1924800765568,             0],
        [            0,             0,             0]],

       [[            0, 1924800767856, 1924796887568],
        [1924800764192,             0,             0]],

       [[            0, 1924145348608,             0],
        [            0,             0,    4294967296]]])

In [108]:
a = np.arange(8).reshape(2, 4)
a

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [109]:
np.zeros_like(a)

array([[0, 0, 0, 0],
       [0, 0, 0, 0]])

In [110]:
np.ones_like(a)

array([[1, 1, 1, 1],
       [1, 1, 1, 1]])

In [112]:
np.full_like(a, 9)

array([[9, 9, 9, 9],
       [9, 9, 9, 9]])

In [119]:
np.full_like(a, range(4))

array([[0, 1, 2, 3],
       [0, 1, 2, 3]])

### 3교시

In [147]:
a = np.arange(4)
a

array([0, 1, 2, 3])

In [138]:
print(a + 2)
print(a - 2)
print(a * 2)
print(a / 2)


[2 3 4 5]
[-2 -1  0  1]
[0 2 4 6]
[0.  0.5 1.  1.5]


In [150]:
b = np.arange(0.5, 4, 1)
b

array([0.5, 1.5, 2.5, 3.5])

In [151]:
a += b

UFuncTypeError: Cannot cast ufunc 'add' output from dtype('float64') to dtype('int64') with casting rule 'same_kind'

In [155]:
b += a
b

array([0.5, 3.5, 6.5, 9.5])

In [156]:
a = np.full((2, 3), [1, 2, 3])
a

array([[1, 2, 3],
       [1, 2, 3]])

In [157]:
b = np.full((3, 2), [2, 1])
b

array([[2, 1],
       [2, 1],
       [2, 1]])

In [158]:
a @ b

array([[12,  6],
       [12,  6]])

In [159]:
a.dot(b)

array([[12,  6],
       [12,  6]])

In [160]:
b.dot(a)

array([[3, 6, 9],
       [3, 6, 9],
       [3, 6, 9]])

In [163]:
a = np.array([[10, 20], [5, 8], [1, 3]])
a

array([[10, 20],
       [ 5,  8],
       [ 1,  3]])

In [164]:
a.sum()

np.int64(47)

In [165]:
a.sum(axis=0)

array([16, 31])

In [166]:
a.sum(axis=1)

array([30, 13,  4])

In [167]:
a = np.array([[3, 4, 8], [1, 3, 5]])
a

array([[3, 4, 8],
       [1, 3, 5]])

In [170]:
print(a.reshape(1, 6))

a.cumsum()

[[3 4 8 1 3 5]]


array([ 3,  7, 15, 16, 19, 24])

In [173]:
print(a)

a.cumsum(axis=0)

[[3 4 8]
 [1 3 5]]


array([[ 3,  4,  8],
       [ 4,  7, 13]])

In [174]:
print(a)

a.cumsum(axis=1)

[[3 4 8]
 [1 3 5]]


array([[ 3,  7, 15],
       [ 1,  4,  9]])

In [180]:
a = np.array((4, 6, 9))
np.sqrt(a)

array([2.        , 2.44948974, 3.        ])

In [181]:
np.log(a)

array([1.38629436, 1.79175947, 2.19722458])

In [182]:
a = np.array([1, 4, 9])
a

array([1, 4, 9])

In [183]:
b = np.full_like(a, 2)
b

array([2, 2, 2])

In [184]:
np.add(a, b)

array([ 3,  6, 11])

In [185]:
np.divide(a, b)

array([0.5, 2. , 4.5])

In [186]:
np.power(a, b)

array([ 1, 16, 81])

In [187]:
a = np.power(np.arange(10), 2)
a

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [188]:
print(a[3])
print(a[-3])

9
49


In [191]:
print(a[1:3])

print(a[-1:-3])

print(a[-3:-1])

[1 4]
[]
[49 64]


In [197]:
print(a[8 : 2 : -1])
print(a[8 : 2 : 1])

print(a[2 : 8 : 1])

print(a[-1 : -7 : -1])

[64 49 36 25 16  9]
[]
[ 4  9 16 25 36 49]
[81 64 49 36 25 16]


In [199]:
a[::-1]

array([81, 64, 49, 36, 25, 16,  9,  4,  1,  0])

In [201]:
a[::-2]

array([81, 49, 25,  9,  1])

In [202]:
a[2:5] = 100
a

array([  0,   1, 100, 100, 100,  25,  36,  49,  64,  81])

In [203]:
a[2:5] = [100, 100, 999]
a

array([  0,   1, 100, 100, 999,  25,  36,  49,  64,  81])

In [204]:
a[2:5] = [100, 100]
a

ValueError: could not broadcast input array from shape (2,) into shape (3,)

In [208]:
a[2:5] = -999
a

array([   0,    1, -999, -999, -999,   25,   36,   49,   64,   81])

In [217]:
b = np.array([999]* 10)
b

array([999, 999, 999, 999, 999, 999, 999, 999, 999, 999])

In [219]:
b[::2] = -1
b

array([ -1, 999,  -1, 999,  -1, 999,  -1, 999,  -1, 999])

In [220]:
b[::2] = np.arange(5)
b

array([  0, 999,   1, 999,   2, 999,   3, 999,   4, 999])

In [222]:
a = np.arange(30).reshape(5, 6)
a

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

In [223]:
a[3]

array([18, 19, 20, 21, 22, 23])

In [224]:
a[-1]

array([24, 25, 26, 27, 28, 29])

In [226]:
# a[-2, ]
a[-2, :]

array([18, 19, 20, 21, 22, 23])

In [227]:
a[2:4]

array([[12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])

In [228]:
a[1:5:2]

array([[ 6,  7,  8,  9, 10, 11],
       [18, 19, 20, 21, 22, 23]])

In [ ]:
a[, -1]

In [229]:
a[:, 1]

array([ 1,  7, 13, 19, 25])

In [231]:
a[:, 2:6]

array([[ 2,  3,  4,  5],
       [ 8,  9, 10, 11],
       [14, 15, 16, 17],
       [20, 21, 22, 23],
       [26, 27, 28, 29]])

In [232]:
a[:, ::2]

array([[ 0,  2,  4],
       [ 6,  8, 10],
       [12, 14, 16],
       [18, 20, 22],
       [24, 26, 28]])

In [234]:
# a[2][4]
a[2, 4]

np.int64(16)

In [235]:
a[1:3, 2:5]

array([[ 8,  9, 10],
       [14, 15, 16]])

In [236]:
# a[:]
# a[:, ]
a[:, :]

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

In [237]:
a[::-1, ::-1]

array([[29, 28, 27, 26, 25, 24],
       [23, 22, 21, 20, 19, 18],
       [17, 16, 15, 14, 13, 12],
       [11, 10,  9,  8,  7,  6],
       [ 5,  4,  3,  2,  1,  0]])

In [238]:
a[:-1, :-1]

array([[ 0,  1,  2,  3,  4],
       [ 6,  7,  8,  9, 10],
       [12, 13, 14, 15, 16],
       [18, 19, 20, 21, 22]])

In [240]:
a = np.arange(24).reshape(2, 3, 4)
a

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [241]:
a[1]

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [243]:
a[:, 1]

array([[ 4,  5,  6,  7],
       [16, 17, 18, 19]])

In [244]:
a[:, 1, 1]

array([ 5, 17])

In [245]:
a[:, :, 1]

array([[ 1,  5,  9],
       [13, 17, 21]])

In [246]:
a[..., 1]

array([[ 1,  5,  9],
       [13, 17, 21]])

In [247]:
a[1, ..., 1]

array([13, 17, 21])

In [248]:
# a[0]
a[0, ...]

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [250]:
a[:, :, 3:]

array([[[ 3],
        [ 7],
        [11]],

       [[15],
        [19],
        [23]]])

In [253]:
a[:, :, 3]

array([[ 3,  7, 11],
       [15, 19, 23]])

In [254]:
a = np.arange(12).reshape(2, 3, 2)
a

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5]],

       [[ 6,  7],
        [ 8,  9],
        [10, 11]]])

In [263]:
print(a.size)

b = a.copy().ravel()
b

12


array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [264]:
b[0] = 999
b

array([999,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11])

In [265]:
a = np.arange(1, 7).reshape(2, 3)
a

array([[1, 2, 3],
       [4, 5, 6]])

In [266]:
# a.T
# a.transpose()
np.transpose(a)

array([[1, 4],
       [2, 5],
       [3, 6]])

In [270]:
np.transpose(a, (0, 1))

array([[1, 2, 3],
       [4, 5, 6]])

In [271]:
np.transpose(a, (1, 0))

array([[1, 4],
       [2, 5],
       [3, 6]])

In [272]:
b = np.arange(1, 13).reshape(3, 2, 2)
b

array([[[ 1,  2],
        [ 3,  4]],

       [[ 5,  6],
        [ 7,  8]],

       [[ 9, 10],
        [11, 12]]])

In [273]:
b.T

array([[[ 1,  5,  9],
        [ 3,  7, 11]],

       [[ 2,  6, 10],
        [ 4,  8, 12]]])

In [274]:
np.transpose(b, (0, 1, 2))

array([[[ 1,  2],
        [ 3,  4]],

       [[ 5,  6],
        [ 7,  8]],

       [[ 9, 10],
        [11, 12]]])

In [275]:
# b.transpose((1, 2, 0))
np.transpose(b, (1, 2, 0))

array([[[ 1,  5,  9],
        [ 2,  6, 10]],

       [[ 3,  7, 11],
        [ 4,  8, 12]]])