### 1교시

In [86]:
import numpy as np

In [87]:
a = np.array([[1, 2, 3], [4, 5, 6]])
a

array([[1, 2, 3],
       [4, 5, 6]])

In [88]:
b = a

b is a

True

In [90]:
print(id(a))
print(id(b))

2705672086960
2705672086960


In [91]:
b[0, 0] = 100
a

array([[100,   2,   3],
       [  4,   5,   6]])

In [92]:
c = a.copy()
c

array([[100,   2,   3],
       [  4,   5,   6]])

In [93]:
print(id(a))
print(id(c))

2705672086960
2705672084944


In [94]:
v = a.reshape(3, 2)
v

array([[100,   2],
       [  3,   4],
       [  5,   6]])

In [95]:
print(id(a))
print(id(v))

2705672086960
2705672088688


In [96]:
v[0, 1] = 200
a

array([[100, 200,   3],
       [  4,   5,   6]])

In [97]:
v.base

array([[100, 200,   3],
       [  4,   5,   6]])

In [98]:
a = np.array([3, 4, 5])
b = np.array([8, 7, 6])

a + b

array([11, 11, 11])

In [99]:
a = np.array([3, 4, 5, 9])
b = np.array([8, 7, 6])

a * b

ValueError: operands could not be broadcast together with shapes (4,) (3,) 

In [100]:
a = np.array([3, 4, 5])
b = 2   # [2, 2, 2]

a + b

array([5, 6, 7])

In [101]:
a = np.array([[1, 2, 3], [4, 5, 6]])

a + 2

array([[3, 4, 5],
       [6, 7, 8]])

In [102]:
x = np.arange(1, 10).reshape(3, 3)
x

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [103]:
y = np.arange(-1, 2)
y

array([-1,  0,  1])

In [104]:
x * y

array([[-1,  0,  3],
       [-4,  0,  6],
       [-7,  0,  9]])

In [105]:
x + y

array([[ 0,  2,  4],
       [ 3,  5,  7],
       [ 6,  8, 10]])

In [106]:
y = np.arange(3, 10, 3).reshape(3, 1)
y

array([[3],
       [6],
       [9]])

In [107]:
np.set_printoptions(precision=2)

In [108]:
x / 2

array([[0.5, 1. , 1.5],
       [2. , 2.5, 3. ],
       [3.5, 4. , 4.5]])

In [109]:
x - y

array([[-2, -1,  0],
       [-2, -1,  0],
       [-2, -1,  0]])

In [110]:
x = np.arange(1, 4)
x

array([1, 2, 3])

In [111]:
y = np.arange(4, 7).reshape(3, 1)
y

array([[4],
       [5],
       [6]])

In [112]:
x * y

array([[ 4,  8, 12],
       [ 5, 10, 15],
       [ 6, 12, 18]])

In [113]:
x / y

array([[0.25, 0.5 , 0.75],
       [0.2 , 0.4 , 0.6 ],
       [0.17, 0.33, 0.5 ]])

In [114]:
x = np.arange(0, 10, 3).reshape(4, 1)
x

array([[0],
       [3],
       [6],
       [9]])

In [115]:
y = np.arange(1, 3)
y

array([1, 2])

In [116]:
x * y

array([[ 0,  0],
       [ 3,  6],
       [ 6, 12],
       [ 9, 18]])

In [117]:
x + y

array([[ 1,  2],
       [ 4,  5],
       [ 7,  8],
       [10, 11]])

In [118]:
x = np.array([0, 10, 20, 30])
x

array([ 0, 10, 20, 30])

In [119]:
np.newaxis is None

True

In [120]:
a = x[None, :]
a

array([[ 0, 10, 20, 30]])

In [121]:
a = x[np.newaxis, :]
a

array([[ 0, 10, 20, 30]])

In [122]:
a = x[:, np.newaxis]
a

array([[ 0],
       [10],
       [20],
       [30]])

In [123]:
a.shape

(4, 1)

In [124]:
b = np.array([1, 2, 3])
b

array([1, 2, 3])

In [125]:
a + b

array([[ 1,  2,  3],
       [11, 12, 13],
       [21, 22, 23],
       [31, 32, 33]])

In [126]:
a * b

array([[ 0,  0,  0],
       [10, 20, 30],
       [20, 40, 60],
       [30, 60, 90]])

In [127]:
x = np.arange(10, 20)
x

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [128]:
print(x[1])
print(x[:5])

11
[10 11 12 13 14]


In [129]:
print(x[[2]])
print(x[[2, 3]])

[12]
[12 13]


In [130]:
x[[2, 3, 5, 8]]

array([12, 13, 15, 18])

In [131]:
x[np.array([5, 3, -4, 8])]

array([15, 13, 16, 18])

In [132]:
x[np.array([10])]

IndexError: index 10 is out of bounds for axis 0 with size 10

In [133]:
x = np.arange(56).reshape(7, 8)
x

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29, 30, 31],
       [32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47],
       [48, 49, 50, 51, 52, 53, 54, 55]])

In [134]:
x[0]

array([0, 1, 2, 3, 4, 5, 6, 7])

In [135]:
x[[0]]

array([[0, 1, 2, 3, 4, 5, 6, 7]])

In [136]:
x[0, 1]

np.int64(1)

In [137]:
x[:, 2:8]

array([[ 2,  3,  4,  5,  6,  7],
       [10, 11, 12, 13, 14, 15],
       [18, 19, 20, 21, 22, 23],
       [26, 27, 28, 29, 30, 31],
       [34, 35, 36, 37, 38, 39],
       [42, 43, 44, 45, 46, 47],
       [50, 51, 52, 53, 54, 55]])

In [138]:
x[, 2:8]

SyntaxError: invalid syntax (664993225.py, line 1)

In [139]:
x[[0], [1]]

array([1])

In [140]:
x[[0, 1]]

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15]])

In [141]:
x[:, [5, 4]]

array([[ 5,  4],
       [13, 12],
       [21, 20],
       [29, 28],
       [37, 36],
       [45, 44],
       [53, 52]])

In [142]:
x[[1, 3]]

array([[ 8,  9, 10, 11, 12, 13, 14, 15],
       [24, 25, 26, 27, 28, 29, 30, 31]])

In [143]:
x[[1, 3], :]

array([[ 8,  9, 10, 11, 12, 13, 14, 15],
       [24, 25, 26, 27, 28, 29, 30, 31]])

In [144]:
x

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29, 30, 31],
       [32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47],
       [48, 49, 50, 51, 52, 53, 54, 55]])

In [145]:
x[[1, 3], [2, 2]]

array([10, 26])

In [146]:
x[[1, 3], [2]]

array([10, 26])

In [147]:
x[[1, 3], 2]

array([10, 26])

In [148]:
x[[1, 3], [3, 3]]

array([11, 27])

In [149]:
x[[1, 3], [3]]

array([11, 27])

In [150]:
x[np.array([0, 2, 4]), np.array([0, 1])]

IndexError: shape mismatch: indexing arrays could not be broadcast together with shapes (3,) (2,) 

In [151]:
x[np.array([0, 2, 4]), np.array([0, 1])]

IndexError: shape mismatch: indexing arrays could not be broadcast together with shapes (3,) (2,) 

In [69]:
x[np.array([0, 2, 4]), 1]

array([ 1, 17, 33])

### 2교시

In [152]:
a = np.arange(6).reshape(3, 2)
a

array([[0, 1],
       [2, 3],
       [4, 5]])

In [154]:
b = np.arange(6, 12).reshape(3, 2)
b

array([[ 6,  7],
       [ 8,  9],
       [10, 11]])

In [155]:
np.vstack((a, b))

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11]])

In [156]:
c = np.arange(20, 24).reshape(2, 2)
c

array([[20, 21],
       [22, 23]])

In [157]:
np.vstack((a, c))

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [20, 21],
       [22, 23]])

In [159]:
np.vstack((a, b, c))

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11],
       [20, 21],
       [22, 23]])

In [160]:
d = np.array([100, 200])
np.vstack((a, d))

array([[  0,   1],
       [  2,   3],
       [  4,   5],
       [100, 200]])

In [161]:
d = np.array([100, 200, 300])
np.vstack((a, d))

ValueError: all the input array dimensions except for the concatenation axis must match exactly, but along dimension 1, the array at index 0 has size 2 and the array at index 1 has size 3

In [163]:
x = np.array([1, 2, 3])
y = np.array([4, 5, 6])

np.vstack((x, y))

array([[1, 2, 3],
       [4, 5, 6]])

In [164]:
np.r_[a, b, c]

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11],
       [20, 21],
       [22, 23]])

In [165]:
a = np.arange(6).reshape(3, 2)
a

array([[0, 1],
       [2, 3],
       [4, 5]])

In [166]:
b = np.arange(10, 19).reshape(3, 3)
b

array([[10, 11, 12],
       [13, 14, 15],
       [16, 17, 18]])

In [167]:
np.hstack((a, b))

array([[ 0,  1, 10, 11, 12],
       [ 2,  3, 13, 14, 15],
       [ 4,  5, 16, 17, 18]])

In [168]:
np.c_[a, b]

array([[ 0,  1, 10, 11, 12],
       [ 2,  3, 13, 14, 15],
       [ 4,  5, 16, 17, 18]])

In [169]:
c = np.array([[10, 20], [30, 40]])
c

array([[10, 20],
       [30, 40]])

In [170]:
np.hstack((a, c))

ValueError: all the input array dimensions except for the concatenation axis must match exactly, but along dimension 0, the array at index 0 has size 3 and the array at index 1 has size 2

In [171]:
np.hstack((np.arange(3), np.arange(10, 15)))

array([ 0,  1,  2, 10, 11, 12, 13, 14])

In [172]:
# vstack
np.r_[np.arange(3), np.arange(10, 15)]

array([ 0,  1,  2, 10, 11, 12, 13, 14])

In [173]:
a = np.arange(6).reshape(3, 2)
a

array([[0, 1],
       [2, 3],
       [4, 5]])

In [174]:
b = np.arange(10, 22).reshape(3, 4)
b

array([[10, 11, 12, 13],
       [14, 15, 16, 17],
       [18, 19, 20, 21]])

In [175]:
np.column_stack((a, b))

array([[ 0,  1, 10, 11, 12, 13],
       [ 2,  3, 14, 15, 16, 17],
       [ 4,  5, 18, 19, 20, 21]])

In [176]:
np.hstack((a, b))

array([[ 0,  1, 10, 11, 12, 13],
       [ 2,  3, 14, 15, 16, 17],
       [ 4,  5, 18, 19, 20, 21]])

In [177]:
np.c_[a, b]

array([[ 0,  1, 10, 11, 12, 13],
       [ 2,  3, 14, 15, 16, 17],
       [ 4,  5, 18, 19, 20, 21]])

In [178]:
x = np.array([1, 2, 3])
y = np.array([10, 20, 30])

np.column_stack((x, y))

array([[ 1, 10],
       [ 2, 20],
       [ 3, 30]])

In [179]:
x[:, np.newaxis]

array([[1],
       [2],
       [3]])

In [180]:
x[np.newaxis, :]

array([[1, 2, 3]])

In [181]:
y[:, np.newaxis]

array([[10],
       [20],
       [30]])

In [182]:
x = np.array([1, 2, 3])
y = np.array([10, 20, 30])

np.column_stack((x[:, np.newaxis], y[:, np.newaxis]))

array([[ 1, 10],
       [ 2, 20],
       [ 3, 30]])

In [183]:
np.hstack((x, y))

array([ 1,  2,  3, 10, 20, 30])

In [184]:
np.column_stack == np.hstack

False

In [185]:
a = np.arange(6).reshape(2, 3)
a

array([[0, 1, 2],
       [3, 4, 5]])

In [187]:
b = np.arange(10, 22).reshape(4, 3)
b

array([[10, 11, 12],
       [13, 14, 15],
       [16, 17, 18],
       [19, 20, 21]])

In [188]:
np.row_stack((a, b))

C:\Users\asus\AppData\Local\Temp\ipykernel_9540\2094407319.py:1: DeprecationWarning: `row_stack` alias is deprecated. Use `np.vstack` directly.
  np.row_stack((a, b))


array([[ 0,  1,  2],
       [ 3,  4,  5],
       [10, 11, 12],
       [13, 14, 15],
       [16, 17, 18],
       [19, 20, 21]])

In [189]:
np.vstack((a, b))

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [10, 11, 12],
       [13, 14, 15],
       [16, 17, 18],
       [19, 20, 21]])

In [190]:
a = np.array([4. , 2. , 1.])
b = np.array([3. , 8. , 7.])

print(np.row_stack((a, b)))

[[4. 2. 1.]
 [3. 8. 7.]]


C:\Users\asus\AppData\Local\Temp\ipykernel_9540\883616519.py:4: DeprecationWarning: `row_stack` alias is deprecated. Use `np.vstack` directly.
  print(np.row_stack((a, b)))


In [192]:
print(np.vstack((a, b)))

[[4. 2. 1.]
 [3. 8. 7.]]


In [198]:
np.row_stack == np.vstack   # True

False

In [199]:
a = np.array([1, 2])
b = np.array([3, 4])
c = np.array([5, 6])

In [200]:
np.concatenate((a, b, c))

array([1, 2, 3, 4, 5, 6])

In [201]:
np.concatenate((a, b, c), axis = 0)

array([1, 2, 3, 4, 5, 6])

In [202]:
np.concatenate((a, b, c), axis=None)

array([1, 2, 3, 4, 5, 6])

In [203]:
x = np.arange(6).reshape(2, 3)
x

array([[0, 1, 2],
       [3, 4, 5]])

In [204]:
y = np.arange(10, 16).reshape(2, 3)
y

array([[10, 11, 12],
       [13, 14, 15]])

In [205]:
z = np.arange(20, 24).reshape(2, 2)
z

array([[20, 21],
       [22, 23]])

In [206]:
np.concatenate((x, y))

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [10, 11, 12],
       [13, 14, 15]])

In [207]:
np.concatenate((x, y), axis=1)

array([[ 0,  1,  2, 10, 11, 12],
       [ 3,  4,  5, 13, 14, 15]])

In [208]:
np.concatenate((x, y, z), axis=1)

array([[ 0,  1,  2, 10, 11, 12, 20, 21],
       [ 3,  4,  5, 13, 14, 15, 22, 23]])

In [209]:
np.concatenate((x, y), axis=None)

array([ 0,  1,  2,  3,  4,  5, 10, 11, 12, 13, 14, 15])

In [210]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

In [212]:
np.stack((a, b))

array([[1, 2, 3],
       [4, 5, 6]])

In [213]:
np.stack((a, b), axis=1)

array([[1, 4],
       [2, 5],
       [3, 6]])

In [215]:
np.stack((a, b), axis = -1)

array([[1, 4],
       [2, 5],
       [3, 6]])

In [216]:
np.stack((a, b), axis = -2)

array([[1, 2, 3],
       [4, 5, 6]])

In [217]:
np.arange(1, 19).reshape(3, 3, 2)

array([[[ 1,  2],
        [ 3,  4],
        [ 5,  6]],

       [[ 7,  8],
        [ 9, 10],
        [11, 12]],

       [[13, 14],
        [15, 16],
        [17, 18]]])

In [218]:
np.arange(16).reshape(2, 2, 4)

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]]])

In [219]:
x = np.arange(6).reshape(2, 3)
x

array([[0, 1, 2],
       [3, 4, 5]])

In [220]:
y = np.arange(10, 16).reshape(2, 3)
y

array([[10, 11, 12],
       [13, 14, 15]])

In [221]:
z = np.arange(20, 26).reshape(2, 3)
z

array([[20, 21, 22],
       [23, 24, 25]])

In [222]:
ax0 = np.stack((x, y, z), axis=0)
ax0

array([[[ 0,  1,  2],
        [ 3,  4,  5]],

       [[10, 11, 12],
        [13, 14, 15]],

       [[20, 21, 22],
        [23, 24, 25]]])

In [224]:
ax0.shape

(3, 2, 3)

In [225]:
ax1 = np.stack((x, y, z), axis=1)
ax1

array([[[ 0,  1,  2],
        [10, 11, 12],
        [20, 21, 22]],

       [[ 3,  4,  5],
        [13, 14, 15],
        [23, 24, 25]]])

In [226]:
ax1.shape

(2, 3, 3)

In [227]:
ax2 = np.stack((x, y, z), axis=2)
ax2

array([[[ 0, 10, 20],
        [ 1, 11, 21],
        [ 2, 12, 22]],

       [[ 3, 13, 23],
        [ 4, 14, 24],
        [ 5, 15, 25]]])

In [228]:
ax2.shape

(2, 3, 3)

In [229]:
x

array([[0, 1, 2],
       [3, 4, 5]])

In [230]:
x[:, :, np.newaxis]

array([[[0],
        [1],
        [2]],

       [[3],
        [4],
        [5]]])

In [231]:
np.expand_dims(x, axis=2)

array([[[0],
        [1],
        [2]],

       [[3],
        [4],
        [5]]])

In [232]:
y

array([[10, 11, 12],
       [13, 14, 15]])

In [233]:
y[:, :, np.newaxis]

array([[[10],
        [11],
        [12]],

       [[13],
        [14],
        [15]]])

In [235]:
np.expand_dims(y, axis=2)

array([[[10],
        [11],
        [12]],

       [[13],
        [14],
        [15]]])

In [236]:
z

array([[20, 21, 22],
       [23, 24, 25]])

In [237]:
z[:, :, np.newaxis]

array([[[20],
        [21],
        [22]],

       [[23],
        [24],
        [25]]])

In [238]:
np.expand_dims(z, axis=2)

array([[[20],
        [21],
        [22]],

       [[23],
        [24],
        [25]]])

In [239]:
np.stack((x, y, z), axis=2)

array([[[ 0, 10, 20],
        [ 1, 11, 21],
        [ 2, 12, 22]],

       [[ 3, 13, 23],
        [ 4, 14, 24],
        [ 5, 15, 25]]])

In [240]:
a = np.arange(1, 13).reshape(3, 4)
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [241]:
c = np.arange(1, 6, 2)
c

array([1, 3, 5])

In [242]:
c[:, np.newaxis]

array([[1],
       [3],
       [5]])

In [243]:
np.hstack((a, c[:, np.newaxis]))

array([[ 1,  2,  3,  4,  1],
       [ 5,  6,  7,  8,  3],
       [ 9, 10, 11, 12,  5]])

In [244]:
np.hstack((a, c))

ValueError: all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 1 dimension(s)

In [245]:
np.hstack((a, np.expand_dims(c, axis=1)))

array([[ 1,  2,  3,  4,  1],
       [ 5,  6,  7,  8,  3],
       [ 9, 10, 11, 12,  5]])

In [248]:
np.column_stack((a, c))

array([[ 1,  2,  3,  4,  1],
       [ 5,  6,  7,  8,  3],
       [ 9, 10, 11, 12,  5]])

In [249]:
np.c_[a, c]

array([[ 1,  2,  3,  4,  1],
       [ 5,  6,  7,  8,  3],
       [ 9, 10, 11, 12,  5]])

In [251]:
a = np.arange(1, 13).reshape(3, 4)
b = np.arange(1, 5)

In [252]:
np.vstack((a, b))

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [ 1,  2,  3,  4]])

In [253]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

In [254]:
np.c_?

Type:        CClass
String form: <numpy.lib._index_tricks_impl.CClass object at 0x00000275F678AB00>
Length:      0
File:        c:\users\asus\anaconda3\envs\dmu\lib\site-packages\numpy\lib\_index_tricks_impl.py
Docstring:  
Translates slice objects to concatenation along the second axis.

This is short-hand for ``np.r_['-1,2,0', index expression]``, which is
useful because of its common occurrence. In particular, arrays will be
stacked along their last axis after being upgraded to at least 2-D with
1's post-pended to the shape (column vectors made out of 1-D arrays).

See Also
--------
column_stack : Stack 1-D arrays as columns into a 2-D array.
r_ : For more detailed documentation.

Examples
--------
>>> import numpy as np
>>> np.c_[np.array([1,2,3]), np.array([4,5,6])]
array([[1, 4],
       [2, 5],
       [3, 6]])
>>> np.c_[np.array([[1,2,3]]), 0, 0, np.array([[4,5,6]])]
array([[1, 2, 3, ..., 4, 5, 6]])

In [255]:
np.c_[a, b]

array([[1, 4],
       [2, 5],
       [3, 6]])

In [256]:
np.column_stack((a, b))

array([[1, 4],
       [2, 5],
       [3, 6]])

In [257]:
x = np.array([[1, 2, 3]])
y = np.array([[4, 5, 6]])

In [258]:
np.c_[x, y]

array([[1, 2, 3, 4, 5, 6]])

In [259]:
np.column_stack((x, y))

array([[1, 2, 3, 4, 5, 6]])

In [261]:
np.column_stack((x, 10, y, 20))

array([[ 1,  2,  3, 10,  4,  5,  6, 20]])

In [262]:
np.r_['1, 2', [1, 2], [[10, 20]]]

array([[ 1,  2, 10, 20]])

In [263]:
np.r_['1, 2', [[1], [2]], [[10], [20]]]

array([[ 1, 10],
       [ 2, 20]])

In [264]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

In [265]:
np.r_[a, b]

array([1, 2, 3, 4, 5, 6])

In [266]:
np.hstack((a, b))

array([1, 2, 3, 4, 5, 6])

In [267]:
np.vstack((a, b))

array([[1, 2, 3],
       [4, 5, 6]])

In [268]:
np.r_[a, 999, b, 999]

array([  1,   2,   3, 999,   4,   5,   6, 999])

In [269]:
np.r_[3:10:3, [0]*2, 5, 6]

array([3, 6, 9, 0, 0, 5, 6])

In [270]:
np.r_[-1:1:6j, [0]*2, 5, 6]

array([-1. , -0.6, -0.2,  0.2,  0.6,  1. ,  0. ,  0. ,  5. ,  6. ])

In [271]:
a = np.array([[0, 1, 2], [3, 4, 5]])

In [272]:
np.r_[a, a, a]

array([[0, 1, 2],
       [3, 4, 5],
       [0, 1, 2],
       [3, 4, 5],
       [0, 1, 2],
       [3, 4, 5]])

In [273]:
np.r_['0', a, a]

array([[0, 1, 2],
       [3, 4, 5],
       [0, 1, 2],
       [3, 4, 5]])

In [274]:
np.r_['-1', a, a]

array([[0, 1, 2, 0, 1, 2],
       [3, 4, 5, 3, 4, 5]])

In [275]:
np.r_['1', a, a]

array([[0, 1, 2, 0, 1, 2],
       [3, 4, 5, 3, 4, 5]])

In [279]:
np.r_['0, 2', a, a]

array([[0, 1, 2],
       [3, 4, 5],
       [0, 1, 2],
       [3, 4, 5]])

In [280]:
np.r_['0, 3', a, a]

array([[[0, 1, 2],
        [3, 4, 5]],

       [[0, 1, 2],
        [3, 4, 5]]])

In [283]:
arr = np.array([1, 2, 3])

print(arr[:, np.newaxis])   # arr[:, None]
print(arr[np.newaxis, :])   # arr[None, :]

[[1]
 [2]
 [3]]
[[1 2 3]]


In [284]:
np.expand_dims(arr, axis=(0, 1))

array([[[1, 2, 3]]])

In [285]:
np.expand_dims(arr, axis=(1, 0))

array([[[1, 2, 3]]])

In [286]:
np.expand_dims(arr, axis=(2, 0))

array([[[1],
        [2],
        [3]]])

In [288]:
np.expand_dims(arr, axis=(2, 0)).shape

(1, 3, 1)

In [290]:
np.expand_dims(np.array([1, 2, 3]), 2)  # axis = 2

AxisError: axis 2 is out of bounds for array of dimension 2

In [293]:
np.expand_dims(np.array([1,2,3]), axis=(1, 2))

array([[[1]],

       [[2]],

       [[3]]])

In [295]:
np.r_['0, 3, 0', [1, 2, 3], [4, 5, 6]]

array([[[1]],

       [[2]],

       [[3]],

       [[4]],

       [[5]],

       [[6]]])

In [296]:
np.r_['0, 3, 0', [1, 2, 3], [4, 5, 6]].shape

(6, 1, 1)

In [297]:
np.r_['0, 3, 1', [1, 2, 3], [4, 5, 6]]

array([[[1],
        [2],
        [3]],

       [[4],
        [5],
        [6]]])

In [298]:
np.r_['0, 3, 1', [1, 2, 3], [4, 5, 6]].shape

(2, 3, 1)

In [299]:
np.expand_dims(np.array([1, 2, 3]), axis=(0, 2))

array([[[1],
        [2],
        [3]]])

In [300]:
np.expand_dims(np.array([4, 5, 6]), axis=(0, 2))

array([[[4],
        [5],
        [6]]])

In [301]:
np.r_['0, 3, 2', [1, 2, 3], [4, 5, 6]]

array([[[1, 2, 3]],

       [[4, 5, 6]]])

In [302]:
np.r_['0, 3, 2', [1, 2, 3], [4, 5, 6]].shape

(2, 1, 3)

In [303]:
np.expand_dims(np.array([1, 2, 3]), axis=(0, 1))

array([[[1, 2, 3]]])

In [304]:
np.expand_dims(np.array([4, 5, 6]), axis=(0, 1))

array([[[4, 5, 6]]])

In [305]:
print(np.r_[[1, 2, 3], [4, 5, 6]])

np.r_['r', [1, 2, 3], [4, 5, 6]]

[1 2 3 4 5 6]


matrix([[1, 2, 3, 4, 5, 6]])

In [307]:
print(np.r_[[1, 2, 3], [4, 5, 6]])

np.r_['c', [1, 2, 3], [4, 5, 6]]

[1 2 3 4 5 6]


matrix([[1],
        [2],
        [3],
        [4],
        [5],
        [6]])

In [308]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

In [309]:
np.hstack((a, b))

array([1, 2, 3, 4, 5, 6])

In [310]:
np.r_[a, b]

array([1, 2, 3, 4, 5, 6])

In [311]:
np.concatenate((a, b))

array([1, 2, 3, 4, 5, 6])

In [312]:
np.c_[a, b]

array([[1, 4],
       [2, 5],
       [3, 6]])

In [313]:
np.vstack((a, b))

array([[1, 2, 3],
       [4, 5, 6]])

In [314]:
np.r_[a[np.newaxis, :], b[np.newaxis, :]]

array([[1, 2, 3],
       [4, 5, 6]])

In [315]:
np.r_['0, 2', a, b]

array([[1, 2, 3],
       [4, 5, 6]])

In [316]:
np.concatenate((a[np.newaxis, :], b[np.newaxis, :]))

array([[1, 2, 3],
       [4, 5, 6]])

### 3교시

In [317]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

In [318]:
np.column_stack((a, b))

array([[1, 4],
       [2, 5],
       [3, 6]])

In [319]:
np.hstack((a[:, np.newaxis], b[:, np.newaxis]))

array([[1, 4],
       [2, 5],
       [3, 6]])

In [320]:
np.c_[a, b]

array([[1, 4],
       [2, 5],
       [3, 6]])

In [321]:
np.r_['1, 2, 0', a, b]

array([[1, 4],
       [2, 5],
       [3, 6]])

In [322]:
np.concatenate(((a[:, np.newaxis], b[:, np.newaxis])), axis=1)

array([[1, 4],
       [2, 5],
       [3, 6]])

In [323]:
np.concatenate?

Call signature:  np.concatenate(*args, **kwargs)
Type:            _ArrayFunctionDispatcher
String form:     <built-in function concatenate>
Docstring:      
concatenate(
    (a1, a2, ...), 
    axis=0, 
    out=None, 
    dtype=None, 
    casting="same_kind"
)

Join a sequence of arrays along an existing axis.

Parameters
----------
a1, a2, ... : sequence of array_like
    The arrays must have the same shape, except in the dimension
    corresponding to `axis` (the first, by default).
axis : int, optional
    The axis along which the arrays will be joined.  If axis is None,
    arrays are flattened before use.  Default is 0.
out : ndarray, optional
    If provided, the destination to place the result. The shape must be
    correct, matching that of what concatenate would have returned if no
    out argument were specified.
dtype : str or dtype
    If provided, the destination array will have this dtype. Cannot be
    provided together with `out`.

    .. versionadded:: 1.20.0

casting 

In [324]:
a = np.array([1, 2, 3, 4])
b = np.array([5, 6, 7, 8])

In [325]:
np.concatenate((a, b))

array([1, 2, 3, 4, 5, 6, 7, 8])

In [327]:
x = np.array([[1, 2], [3, 4]])
x

array([[1, 2],
       [3, 4]])

In [331]:
y = np.array([[5, 6]])
y

array([[5, 6]])

In [332]:
np.concatenate((x, y))

array([[1, 2],
       [3, 4],
       [5, 6]])

In [333]:
x.flatten()

array([1, 2, 3, 4])

In [334]:
y.flatten()

array([5, 6])

In [335]:
np.concatenate((x, y), axis=None)

array([1, 2, 3, 4, 5, 6])

In [337]:
x = np.arange(9)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [338]:
s = np.split(x, 3)
s

[array([0, 1, 2]), array([3, 4, 5]), array([6, 7, 8])]

In [339]:
type(s)

list

In [340]:
np.split(x, 4)

ValueError: array split does not result in an equal division

In [341]:
x = np.arange(1, 10)
x

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [342]:
np.split(x, [2, 6])

[array([1, 2]), array([3, 4, 5, 6]), array([7, 8, 9])]

In [343]:
s = np.split(x, 3)
s

[array([1, 2, 3]), array([4, 5, 6]), array([7, 8, 9])]

In [344]:
y = np.arange(10, 61, 10)
y

array([10, 20, 30, 40, 50, 60])

In [345]:
np.split(y, [2, 3, 4])

[array([10, 20]), array([30]), array([40]), array([50, 60])]

In [346]:
np.split(y, [2, 3, 4, 6])

[array([10, 20]),
 array([30]),
 array([40]),
 array([50, 60]),
 array([], dtype=int64)]

In [347]:
y[4:6]

array([50, 60])

In [348]:
y[4:]

array([50, 60])

In [349]:
a = np.arange(24).reshape(2, 12)
a

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23]])

In [350]:
np.hsplit(a, 3)

[array([[ 0,  1,  2,  3],
        [12, 13, 14, 15]]),
 array([[ 4,  5,  6,  7],
        [16, 17, 18, 19]]),
 array([[ 8,  9, 10, 11],
        [20, 21, 22, 23]])]

In [351]:
np.split(a, 3, axis=1)

[array([[ 0,  1,  2,  3],
        [12, 13, 14, 15]]),
 array([[ 4,  5,  6,  7],
        [16, 17, 18, 19]]),
 array([[ 8,  9, 10, 11],
        [20, 21, 22, 23]])]

In [352]:
np.split(a, 4, axis=1)

[array([[ 0,  1,  2],
        [12, 13, 14]]),
 array([[ 3,  4,  5],
        [15, 16, 17]]),
 array([[ 6,  7,  8],
        [18, 19, 20]]),
 array([[ 9, 10, 11],
        [21, 22, 23]])]

In [353]:
a = np.arange(24).reshape(2, 12)
a

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23]])

In [354]:
np.split(a, [3, 5, 7], axis=1)

[array([[ 0,  1,  2],
        [12, 13, 14]]),
 array([[ 3,  4],
        [15, 16]]),
 array([[ 5,  6],
        [17, 18]]),
 array([[ 7,  8,  9, 10, 11],
        [19, 20, 21, 22, 23]])]

In [355]:
b = np.arange(24).reshape(6, 4)
b

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [356]:
np.split(b, 3, axis=0)

[array([[0, 1, 2, 3],
        [4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11],
        [12, 13, 14, 15]]),
 array([[16, 17, 18, 19],
        [20, 21, 22, 23]])]

In [357]:
np.split(b, [2, 4, 6], axis=0)

[array([[0, 1, 2, 3],
        [4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11],
        [12, 13, 14, 15]]),
 array([[16, 17, 18, 19],
        [20, 21, 22, 23]]),
 array([], shape=(0, 4), dtype=int64)]

In [358]:
a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [359]:
np.hsplit(a, 2)

[array([0, 1, 2, 3, 4]), array([5, 6, 7, 8, 9])]

In [360]:
np.hsplit(a, [2, 5])

[array([0, 1]), array([2, 3, 4]), array([5, 6, 7, 8, 9])]

In [361]:
np.vsplit(a, 2)

ValueError: vsplit only works on arrays of 2 or more dimensions

In [362]:
a = np.arange(18).reshape(6, 3)
a

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17]])

In [363]:
np.vsplit(a, 3)

[array([[0, 1, 2],
        [3, 4, 5]]),
 array([[ 6,  7,  8],
        [ 9, 10, 11]]),
 array([[12, 13, 14],
        [15, 16, 17]])]

In [364]:
np.vsplit(a, 4)

ValueError: array split does not result in an equal division

In [365]:
np.vsplit(a, (1, 4, 6))

[array([[0, 1, 2]]),
 array([[ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11]]),
 array([[12, 13, 14],
        [15, 16, 17]]),
 array([], shape=(0, 3), dtype=int64)]

In [366]:
a[:1, :]

array([[0, 1, 2]])

In [367]:
a[4:6, :]

array([[12, 13, 14],
       [15, 16, 17]])

In [368]:
a[6:, :]

array([], shape=(0, 3), dtype=int64)

In [369]:
x = np.arange(32).reshape(4, 4, 2)
x

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5],
        [ 6,  7]],

       [[ 8,  9],
        [10, 11],
        [12, 13],
        [14, 15]],

       [[16, 17],
        [18, 19],
        [20, 21],
        [22, 23]],

       [[24, 25],
        [26, 27],
        [28, 29],
        [30, 31]]])

In [370]:
np.hsplit(x, 2)

[array([[[ 0,  1],
         [ 2,  3]],
 
        [[ 8,  9],
         [10, 11]],
 
        [[16, 17],
         [18, 19]],
 
        [[24, 25],
         [26, 27]]]),
 array([[[ 4,  5],
         [ 6,  7]],
 
        [[12, 13],
         [14, 15]],
 
        [[20, 21],
         [22, 23]],
 
        [[28, 29],
         [30, 31]]])]

In [371]:
np.split(x, 2, axis=1)

[array([[[ 0,  1],
         [ 2,  3]],
 
        [[ 8,  9],
         [10, 11]],
 
        [[16, 17],
         [18, 19]],
 
        [[24, 25],
         [26, 27]]]),
 array([[[ 4,  5],
         [ 6,  7]],
 
        [[12, 13],
         [14, 15]],
 
        [[20, 21],
         [22, 23]],
 
        [[28, 29],
         [30, 31]]])]

In [372]:
x[:, :2, :]

array([[[ 0,  1],
        [ 2,  3]],

       [[ 8,  9],
        [10, 11]],

       [[16, 17],
        [18, 19]],

       [[24, 25],
        [26, 27]]])

In [373]:
x[:, 2:, :]

array([[[ 4,  5],
        [ 6,  7]],

       [[12, 13],
        [14, 15]],

       [[20, 21],
        [22, 23]],

       [[28, 29],
        [30, 31]]])

In [374]:
np.hsplit(x, [1, 3])

[array([[[ 0,  1]],
 
        [[ 8,  9]],
 
        [[16, 17]],
 
        [[24, 25]]]),
 array([[[ 2,  3],
         [ 4,  5]],
 
        [[10, 11],
         [12, 13]],
 
        [[18, 19],
         [20, 21]],
 
        [[26, 27],
         [28, 29]]]),
 array([[[ 6,  7]],
 
        [[14, 15]],
 
        [[22, 23]],
 
        [[30, 31]]])]

In [375]:
x = np.arange(32).reshape(4, 4, 2)

In [376]:
np.vsplit(x, 2)

[array([[[ 0,  1],
         [ 2,  3],
         [ 4,  5],
         [ 6,  7]],
 
        [[ 8,  9],
         [10, 11],
         [12, 13],
         [14, 15]]]),
 array([[[16, 17],
         [18, 19],
         [20, 21],
         [22, 23]],
 
        [[24, 25],
         [26, 27],
         [28, 29],
         [30, 31]]])]

In [377]:
np.split(x, 2, axis=0)

[array([[[ 0,  1],
         [ 2,  3],
         [ 4,  5],
         [ 6,  7]],
 
        [[ 8,  9],
         [10, 11],
         [12, 13],
         [14, 15]]]),
 array([[[16, 17],
         [18, 19],
         [20, 21],
         [22, 23]],
 
        [[24, 25],
         [26, 27],
         [28, 29],
         [30, 31]]])]

In [378]:
x[:2, :, :]

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5],
        [ 6,  7]],

       [[ 8,  9],
        [10, 11],
        [12, 13],
        [14, 15]]])

In [379]:
x[2:, :, :]

array([[[16, 17],
        [18, 19],
        [20, 21],
        [22, 23]],

       [[24, 25],
        [26, 27],
        [28, 29],
        [30, 31]]])

In [380]:
np.vsplit(x, [1, 3])

[array([[[0, 1],
         [2, 3],
         [4, 5],
         [6, 7]]]),
 array([[[ 8,  9],
         [10, 11],
         [12, 13],
         [14, 15]],
 
        [[16, 17],
         [18, 19],
         [20, 21],
         [22, 23]]]),
 array([[[24, 25],
         [26, 27],
         [28, 29],
         [30, 31]]])]

In [381]:
x[:1, :, :]

array([[[0, 1],
        [2, 3],
        [4, 5],
        [6, 7]]])

In [382]:
x[1:3]

array([[[ 8,  9],
        [10, 11],
        [12, 13],
        [14, 15]],

       [[16, 17],
        [18, 19],
        [20, 21],
        [22, 23]]])

In [384]:
x[3:]

array([[[24, 25],
        [26, 27],
        [28, 29],
        [30, 31]]])

In [385]:
x = np.arange(9)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [386]:
np.array_split(x, 2)

[array([0, 1, 2, 3, 4]), array([5, 6, 7, 8])]

In [387]:
np.split(x, 2)

ValueError: array split does not result in an equal division

In [388]:
np.array_split(x, 3)

[array([0, 1, 2]), array([3, 4, 5]), array([6, 7, 8])]

In [389]:
np.array_split(x, 4)

[array([0, 1, 2]), array([3, 4]), array([5, 6]), array([7, 8])]

In [390]:
np.array_split(x, 5)

[array([0, 1]), array([2, 3]), array([4, 5]), array([6, 7]), array([8])]

In [391]:
np.array_split(x, [2, 4, 8])

[array([0, 1]), array([2, 3]), array([4, 5, 6, 7]), array([8])]

In [392]:
a = np.arange(35).reshape(7, 5)
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34]])

In [393]:
np.array_split(a, 2, axis=0)

[array([[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19]]),
 array([[20, 21, 22, 23, 24],
        [25, 26, 27, 28, 29],
        [30, 31, 32, 33, 34]])]

In [394]:
np.array_split(a, 2, axis=1)

[array([[ 0,  1,  2],
        [ 5,  6,  7],
        [10, 11, 12],
        [15, 16, 17],
        [20, 21, 22],
        [25, 26, 27],
        [30, 31, 32]]),
 array([[ 3,  4],
        [ 8,  9],
        [13, 14],
        [18, 19],
        [23, 24],
        [28, 29],
        [33, 34]])]

In [395]:
np.array_split(a, 4, axis=0)

[array([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]]),
 array([[10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19]]),
 array([[20, 21, 22, 23, 24],
        [25, 26, 27, 28, 29]]),
 array([[30, 31, 32, 33, 34]])]

In [396]:
np.array_split(a, 4, axis=1)

[array([[ 0,  1],
        [ 5,  6],
        [10, 11],
        [15, 16],
        [20, 21],
        [25, 26],
        [30, 31]]),
 array([[ 2],
        [ 7],
        [12],
        [17],
        [22],
        [27],
        [32]]),
 array([[ 3],
        [ 8],
        [13],
        [18],
        [23],
        [28],
        [33]]),
 array([[ 4],
        [ 9],
        [14],
        [19],
        [24],
        [29],
        [34]])]

In [397]:
np.array_split(a, [2, 4], axis=0)

[array([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]]),
 array([[10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19]]),
 array([[20, 21, 22, 23, 24],
        [25, 26, 27, 28, 29],
        [30, 31, 32, 33, 34]])]

In [398]:
np.array_split(a, [2, 4], axis=1)

[array([[ 0,  1],
        [ 5,  6],
        [10, 11],
        [15, 16],
        [20, 21],
        [25, 26],
        [30, 31]]),
 array([[ 2,  3],
        [ 7,  8],
        [12, 13],
        [17, 18],
        [22, 23],
        [27, 28],
        [32, 33]]),
 array([[ 4],
        [ 9],
        [14],
        [19],
        [24],
        [29],
        [34]])]

In [400]:
x = np.arange(24).reshape(2, 2, 6)
x

array([[[ 0,  1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10, 11]],

       [[12, 13, 14, 15, 16, 17],
        [18, 19, 20, 21, 22, 23]]])

In [401]:
np.array_split(x, 4, axis=2)

[array([[[ 0,  1],
         [ 6,  7]],
 
        [[12, 13],
         [18, 19]]]),
 array([[[ 2,  3],
         [ 8,  9]],
 
        [[14, 15],
         [20, 21]]]),
 array([[[ 4],
         [10]],
 
        [[16],
         [22]]]),
 array([[[ 5],
         [11]],
 
        [[17],
         [23]]])]

In [402]:
np.split(x, [2, 4, 5], axis=2)

[array([[[ 0,  1],
         [ 6,  7]],
 
        [[12, 13],
         [18, 19]]]),
 array([[[ 2,  3],
         [ 8,  9]],
 
        [[14, 15],
         [20, 21]]]),
 array([[[ 4],
         [10]],
 
        [[16],
         [22]]]),
 array([[[ 5],
         [11]],
 
        [[17],
         [23]]])]

In [403]:
np.split(x, [2, 4, 5], axis=2)

[array([[[ 0,  1],
         [ 6,  7]],
 
        [[12, 13],
         [18, 19]]]),
 array([[[ 2,  3],
         [ 8,  9]],
 
        [[14, 15],
         [20, 21]]]),
 array([[[ 4],
         [10]],
 
        [[16],
         [22]]]),
 array([[[ 5],
         [11]],
 
        [[17],
         [23]]])]

In [404]:
x[:, :, 5:]

array([[[ 5],
        [11]],

       [[17],
        [23]]])

In [405]:
x = np.arange(24).reshape(2, 2, 6)
x

array([[[ 0,  1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10, 11]],

       [[12, 13, 14, 15, 16, 17],
        [18, 19, 20, 21, 22, 23]]])

In [406]:
np.dsplit(x, 2)

[array([[[ 0,  1,  2],
         [ 6,  7,  8]],
 
        [[12, 13, 14],
         [18, 19, 20]]]),
 array([[[ 3,  4,  5],
         [ 9, 10, 11]],
 
        [[15, 16, 17],
         [21, 22, 23]]])]

In [407]:
np.split(x, 2, axis=2)

[array([[[ 0,  1,  2],
         [ 6,  7,  8]],
 
        [[12, 13, 14],
         [18, 19, 20]]]),
 array([[[ 3,  4,  5],
         [ 9, 10, 11]],
 
        [[15, 16, 17],
         [21, 22, 23]]])]

In [408]:
np.dsplit(x, 3)

[array([[[ 0,  1],
         [ 6,  7]],
 
        [[12, 13],
         [18, 19]]]),
 array([[[ 2,  3],
         [ 8,  9]],
 
        [[14, 15],
         [20, 21]]]),
 array([[[ 4,  5],
         [10, 11]],
 
        [[16, 17],
         [22, 23]]])]

In [409]:
np.dsplit(x, 4)

ValueError: array split does not result in an equal division

In [410]:
np.dsplit(x, [2, 4, 5])

[array([[[ 0,  1],
         [ 6,  7]],
 
        [[12, 13],
         [18, 19]]]),
 array([[[ 2,  3],
         [ 8,  9]],
 
        [[14, 15],
         [20, 21]]]),
 array([[[ 4],
         [10]],
 
        [[16],
         [22]]]),
 array([[[ 5],
         [11]],
 
        [[17],
         [23]]])]

In [411]:
rg = np.random.default_rng(12345)
rg

Generator(PCG64) at 0x275F6EEDC40

In [412]:
r = rg.random()
r

0.22733602246716966

In [413]:
rg.random(5)

array([0.32, 0.8 , 0.68, 0.39, 0.33])

In [414]:
rg.random((4, 3))

array([[0.6 , 0.19, 0.67],
       [0.94, 0.25, 0.95],
       [0.67, 0.1 , 0.44],
       [0.89, 0.7 , 0.33]])

In [415]:
rg = np.random.default_rng(12345)
r = rg.integers(low=0, high=10, size=3)
r

array([6, 2, 7])

In [416]:
rg.integers(1, 7, (3, 4))

array([[2, 2, 5, 4],
       [5, 6, 3, 6],
       [2, 4, 4, 2]])

In [417]:
rg = np.random.default_rng(seed=42)
rg.standard_normal(10)

array([ 0.3 , -1.04,  0.75,  0.94, -1.95, -1.3 ,  0.13, -0.32, -0.02,
       -0.85])

In [418]:
rg.standard_normal((4, 3))

array([[ 0.88,  0.78,  0.07],
       [ 1.13,  0.47, -0.86],
       [ 0.37, -0.96,  0.88],
       [-0.05, -0.18, -0.68]])